// Code generated by "stringer -type stage -linecomment"; DO NOT EDIT.

package gotsr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[sUnknown - -1]
	_ = x[sInitialise-0]
	_ = x[sDetach-1]
	_ = x[sRunning-2]
}

const _stage_name = "UNKNOWNINITDETACHRUN"

var _stage_index = [...]uint8{0, 7, 11, 17, 20}

func (i stage) String() string {
	i -= -1
	if i < 0 || i >= stage(len(_stage_index)-1) {
		return "stage(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _stage_name[_stage_index[i]:_stage_index[i+1]]
}
